package org.supportcompact.events;

public enum Event {
    REFRESH_ACCOUNT, BANK_MANDATE_SUBMITTED, PRIVACY_PAGE, TERMS_AND_CONDITIONS_PAGE,
    ISFROMNEWBANKMANDATE, ISFROMBANKMANDATE, NEFTRTGS, ISMOBILEVERIFIED, ISEMAILVERIFIED,
    ISMOBILEVERIFIEDBACK, ISEMAILVERIFIEDBACK, ISFROMTRANSACTIONSUCCESS, ISGOALADDED, ONLOGOUT,
    DISMISS_LOADING, BANK_MANDATE_INSTRUCTIONS, RESET_OPTION_MENU, ON_PAYMENT_REDIRECTED
}
